name: weather_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  json_annotation: ^4.5.0
  provider: ^6.0.3
  mockito: ^5.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  test:


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
